name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Debug - List Backend Directory
      run: ls -la ./Backend

    - name: Debug - Show Lock File
      run: cat ./Backend/package-lock.json

    - name: Check for lock file
      run: |
        if [ ! -f ./Backend/package-lock.json ]; then
          echo "Error: Dependencies lock file is not found in ./Backend."
          exit 1
        fi

    - name: Install dependencies
      run: npm ci
      working-directory: ./Backend

    - name: Create .env file with secret
      run: |
        touch ./Backend/.env
        echo "${{secrets.PROD}}" > ./Backend/.env

    - name: Restart PM2
      run: |
        pm2 restart Backend || pm2 start ./Backend/server.js --name Backend
      working-directory: ./Backend
