name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Manually install dependencies in the Backend folder
    - name: Install dependencies
      run: |
        cd Backend
        npm ci  # Install dependencies in the Backend directory
      working-directory: ./Backend  # Ensures npm ci is executed in the Backend folder

    # Restart PM2 from the Backend directory
    - name: Restart PM2
      run: |
        cd Backend
        pm2 restart Backend
      working-directory: ./Backend  # Ensures PM2 is restarted in the Backend directory
