name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # This caches npm dependencies but won't affect your working directory

    # Install dependencies manually in the Backend folder
    - name: Install dependencies in Backend
      run: |
        cd Backend  # Change to the Backend directory
        npm ci  # Install dependencies in the Backend folder
      working-directory: ./Backend  # Ensure npm ci is executed in the Backend folder

    # Restart PM2 from the Backend directory
    - name: Restart PM2 in Backend
      run: |
        cd Backend  # Change to the Backend directory
        pm2 restart Backend  # Restart PM2 with the correct config
      working-directory: ./Backend  # Ensure PM2 is restarted in the Backend folder
