name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        working-directory: ./Backend  # Make sure this is pointing to the Backend directory

    - name: Install dependencies
      run: npm ci
      working-directory: ./Backend  # Ensure you're installing dependencies in the Backend folder

    - name: Restart PM2
      run: pm2 restart Backend
      working-directory: ./Backend  # Ensure you're restarting PM2 from the Backend folder
